# Generated by Django 5.0.2 on 2024-02-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
