# Generated by Django 5.0.2 on 2024-02-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_description_alter_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto.categoria'),
        ),
    ]
